# fly.toml app configuration file generated for paab-website on 2025-12-04T18:00:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'paab-website'
primary_region = 'jnb'

[build]

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "error"
  DB_CONNECTION = "sqlite"
  DB_DATABASE = "/var/www/html/database/database.sqlite"
  SESSION_DRIVER = "file"
  CACHE_STORE = "file"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "paab_data"
  destination = "/var/www/html/database"
  processes = ["app"]
